### PR TITLE
Working with GMP library now

### PR DESCRIPTION
**Pull request by Alex-Kreitzberg**
So I templated my previous algorithm, added a new `isLikelyPrime` function to incorporate GMP's primality test. The algorithm works unchanged!

### CODE REVIEW

**Comment by rossica** [comment]
You've got some conflicts in this PR.
It looks like you did all your work in a branch that was stale, since these merge conflicts look like they redo changes that were already done.
I think you should look into doing a `git rebase` to re-base your changes onto the correct parent change to help resolve these merge conflicts.

**Comment by Alex-Kreitzberg** [comment]
I see, that makes sense. I'll play with git and try to learn how to fix that.

**Comment by Alex-Kreitzberg** [comment]
Man, I really messed up my repository somehow. This git stuff is subtle :p

**Comment by Alex-Kreitzberg** [comment]
So I didn't get rebase to work in a way, where I didn't think there was going to be a mistake. The mistake I made, was that I didn't merge my repository with your repository after you accept my first pull request. After major changes in the core project, I'm supposed to make sure my version is consistent with it, but I didn't.

**Comment by Alex-Kreitzberg** [comment]
Now I'm a little concerned about how complicated the commit history is.

**Comment by Alex-Kreitzberg** [comment]
I think I'm doing the git thing wrong, don't accept this pull request yet.

**Pull request closed without merging**
